Fix compilation with clang
Fix compilation error:
```
clang -Wall -Werror -Wextra -std=c99 -pedantic -Wno-unused-parameter stag.c view.c data.c -o stag -lncurses -lm -D_DEFAULT_SOURCE 
stag.c:50:11: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
void usage(){
```